pom.xml, src/main/java/org/auscope/portal/server/CORSAdvice.java, src/main/java/org/auscope/portal/server/config/KnownLayers.java, src/main/java/org/auscope/portal/server/web/controllers/JobListController.java, src/main/java/org/auscope/portal/server/web/controllers/PurchaseController.java, src/main/java/org/auscope/portal/server/web/service/SolutionResponse.java, src/main/java/org/auscope/portal/server/web/service/VGLCryptoService.java, src/main/java/org/auscope/portal/server/web/service/scm/Entry.java, src/test/java/org/auscope/portal/server/vegl/TestVGLJobStatusAndLogReader.java, src/test/java/org/auscope/portal/server/web/controllers/TestJobDownloadController.java, src/test/java/org/auscope/portal/server/web/controllers/TestJobListController.java, src/test/java/org/auscope/portal/server/web/service/ANVGLProvenanceServiceTest.java
Fixed some deprecation warnings.
Removed some unused variables and code.
Got rid of some unnecessary POM library version declarations that were overriding managed libraries.
Added a few inferred generic types where it was obvious.
Fixed some improper static method usage.
Added a few generated serialVersionUIDs in serializable classes.
=> Fix warnings (Stage 1)

src/main/java/org/auscope/portal/mineraloccurrence/MineralTenementCCFilter.java, src/main/java/org/auscope/portal/mineraloccurrence/MineralTenementFilter.java, src/main/java/org/auscope/portal/server/web/controllers/MineralTenementController.java, src/main/java/org/auscope/portal/server/web/service/MineralTenementService.java, src/test/java/org/auscope/portal/mineraloccurrence/TestMineralTenementFilter.java
Please test. It should work now, except for QLD. It's because it's an ArcGIS one and it has a special handling in its own class. I will ask Vincent to fix it.
=> AUS-3450: Mineral tenement filters don't work

.gitignore, src/main/java/org/auscope/portal/server/config/AppContext.java, src/main/java/org/auscope/portal/server/web/service/monitor/KnownLayerStatusMonitor.java, src/test/java/org/auscope/portal/server/web/service/monitor/TestKnownLayerServiceStatusMonitor.java
Added Quartz job to regularly update service status for KnownLayers
=> Aus 3195 speed up known layer request

src/main/java/org/auscope/portal/server/web/controllers/IRISController.java
Modify KML returned from IRISController.
=> AUS-3592 Fix IRIS layers click

pom.xml
I have upgraded versions to fix vulnerabilities
=> AUS-3647 Added & updated pom file dependencies to enable test & build

src/main/java/org/auscope/portal/gsml/SF0BoreholeFilter.java
fixed NVCL layer sld issue with newer geoservers by removing Or filter
=> fixed NVCL layer sld issue with newer geoservers by removing Or filter

pom.xml
changed package repository from cgmaven to azure devops aus-mvn : https://dev.azure.com/CSIROMineralResources/AuScope%20AVRE/_packaging?_a=feed&feed=aus-mvn
=> changed package repository from cgmaven to azure devops aus-mvn

src/main/resources/layers.yaml, src/main/resources/org/auscope/portal/server/web/service/cloud/nci-run.job.tpl
* Add GRACE and World Boundaries layers.yaml
* Small fix to closing log tag.
=> AUS-3532 GRACE Port

pom.xml, src/main/java/org/auscope/portal/server/config/AppContext.java, src/main/java/org/auscope/portal/server/web/CatalogServicesHealthIndicator.java, src/main/resources/application.yaml.default
added springboot actuator info and health metrics to display real-time health of a running API.  Also added git info to the build to make it available via the info endpoint.
=> added springboot actuator info and health

src/main/java/org/auscope/portal/server/web/controllers/IRISController.java
=> AUS-3714 Modify getIRISStations to extract channel's details 

src/main/resources/layers.yaml
Add Loop3D layers to layer list.
=> AUS-3698-Loop3D-Layers

src/main/resources/layers.yaml
=> AUS-3725-AusLAMP-Layers

src/main/resources/application.yaml.default
updated NVCL Analytics Url to the new azure service.  this will need to be propagated through to the actual application.yamls running on the servers.
=> updated NVCL Analytics Url

src/main/java/org/auscope/portal/server/config/AppContext.java, src/main/java/org/auscope/portal/server/web/controllers/BaseCloudController.java, src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java, src/main/java/org/auscope/portal/server/web/controllers/JobDownloadController.java, src/main/java/org/auscope/portal/server/web/controllers/JobListController.java, src/main/java/org/auscope/portal/server/web/controllers/PurchaseController.java, src/main/java/org/auscope/portal/server/web/controllers/ScriptBuilderController.java, src/main/java/org/auscope/portal/server/web/security/VEGLSecurityConfig.java, src/main/java/org/auscope/portal/server/web/security/aaf/AAFAuthenticationFilter.java, src/main/java/org/auscope/portal/server/web/security/aaf/AAFAuthenticationRedirect.java, src/main/java/org/auscope/portal/server/web/security/aaf/JWTManagement.java, src/main/java/org/auscope/portal/server/web/service/ANVGLProvenanceService.java, src/main/java/org/auscope/portal/server/web/service/NVCL2_0_DataService.java, src/main/java/org/auscope/portal/server/web/service/VGLCryptoService.java, src/main/resources/application.yaml.default
Restructure the application.yaml.default, and update all necessary project references.
A separate Python script can update existing yaml files.
=> AUS-3771 Tidy up application.yaml

src/main/java/org/auscope/portal/server/config/AppContext.java, src/main/resources/application.yaml.default
Increased delay of known layers caching startup and made delay configurable.
=> AUS-3768 KnownLayers Caching Startup

pom.xml, src/main/java/org/auscope/portal/server/config/AppContext.java, src/test/java/org/auscope/portal/server/web/service/monitor/TestKnownLayerServiceStatusMonitor.java
=> AUS-3808 Improved Search

src/main/resources/layers.yaml
Added GA's Geochronology and Isotopes layers to portal.
=> AUS-3802 Geochronology and Isotopes layers

src/main/java/org/auscope/portal/server/config/AppContext.java, src/main/resources/application.yaml.default
Explicitly set a time zone (Australian Eastern) for known layers CRON job.
=> AUS-3685-2 Set CRON time zone

src/main/db/mysql/auscope-schema-mysql.sql, src/main/db/postgres/auscope-schema-pg.sql, src/main/java/org/auscope/portal/server/config/AppContext.java, src/main/java/org/auscope/portal/server/state/PortalState.java, src/main/java/org/auscope/portal/server/web/controllers/PortalStateController.java, src/main/java/org/auscope/portal/server/web/repositories/PortalStateRepository.java, src/main/java/org/auscope/portal/server/web/service/PortalStateService.java
Added controller, service and repository for portal states.
Updated DB schemas with new states table.
Renamed DB schemas.
=> AUS-3906 States in DB

.github/coverage/jacoco.csv, src/main/java/org/auscope/portal/gsml/SF0BoreholeFilter.java, src/main/java/org/auscope/portal/server/web/controllers/SF0BoreholeController.java, src/main/java/org/auscope/portal/server/web/service/SF0BoreholeService.java, src/test/java/org/auscope/portal/server/web/service/TestSF0BoreholeService.java
Allow omitting gsmlp:shape property from WFS download filter.
=> AUS-3837 datasetUrlSupportedLayer

pom.xml, src/main/java/org/auscope/portal/server/config/AppContext.java, src/main/resources/bootstrap.yaml
added optional azure appconfiguration.  this should not impact existing application.yamls. 
To use it add a bootstrap.yaml file with your azure app configuration connection string and any filters.
=> added optional azure appconfiguration

src/main/resources/layers.yaml
Added Geophysical Grid Gravity, Magnetics and Radiometrics layers.
Created a Boundaries layer group, shifted World Boundaries from GRACE.
=> AUS-3979 TMI Layers

.github/workflows/build-dev.yml, .github/workflows/build-prod-release.yml, Dockerfile.github, src/main/resources/application-test.yaml
changed build profiles to match our current dev/prod environments. Updated github actions that build and push docker images.
=> Aus 4042 - update build profiles and fix github build actions

src/main/java/org/auscope/portal/server/web/controllers/IRISController.java
This fixes the problem of "Seismographs in Schools" layer not loading because it does not have an end date.
This is because it is still an ongoing project.
=> AUS-4193 Fix missing end date problem

src/main/resources/layers.yaml
Added an initialBBox parameter for 2 Tasmanian layers
=> AUS-3883 Tasmanian Layer Zoom

src/main/resources/layers.yaml
New DAS layer added to featured layers.
=> Add DAS layer
